name: Deploy to Raspberry Pi

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Create new virtual env and activate it
        run: |
          python3 -m venv UptimeMonitor
          source UptimeMonitor/bin/activate
          python3 -m pip install -r requirements.txt
  deploy:
    runs-on: self-hosted
    needs: build
    
    steps:
      - name: Kill existing process
        run: |
          if [ ! -f .pid ] then
            pkill $(cat .pid)
          fi
          pkill -9 -f fastapi

      - name: Run uptime.py and api.py
        run: |
          source UptimeMonitor/bin/activate
          python3 uptime.py --target 8.8.8.8 --period 2000 &
          nohup fastapi run api.py &> api.log &