name: Deploy to Raspberry Pi

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  stop:
    runs-on: self-hosted

    steps:
      - name: Kill uptime.py
        run: |
          echo $HOME
          if [ -f $HOME/uptime_logs/.pid ]; then
              pkill $(cat $HOME/uptime_logs/.pid)
          fi
      - name: Kill api.py
        run: |
          pkill -9 -f fastapi || true
          pkill -9 -f yes || true
  build:
    runs-on: self-hosted
    needs: stop

    steps:
      - uses: actions/checkout@v2
      - name: Create new virtual env and activate it
        run: |
          python3 -m venv UptimeMonitor
          source UptimeMonitor/bin/activate
          python3 -m pip install -r requirements.txt
  deploy:
    runs-on: self-hosted
    needs: build
    
    steps:
      - name: Run uptime.py and api.py
        run: |
          RUNNER_TRACKING_ID=""
          source UptimeMonitor/bin/activate
          chmod 777 start_uptime.sh
          chmod 777 start_api.sh
          ./start_uptime.sh
          ./start_api.sh